### ISSUE TITLE
Problem with evaluate_trained_models.py

### ISSUE THREAD

**Issue by ocekic** [georkara/Chargym-Charging-Station#3]
Hello,

Thanks for this repo.

I cloned this repo and wanted to use it for education purposes. I succeded the configuration of the env and the 3 main algorithms works (RBC, DDPG and PPO). The code check_main.py don't show problems.

But I have a problem, when i run the evaluate_trained_models.py, he can't access to the folder the others codes made. I have this error : FileNotFoundError: [Errno 2] No such file or directory: 'models\\DDPG-1685441307\\80000.zip.zip'.
I tried to change the relative path but it doesn't work.

The Tensorboard also cannot access the files and the web app is not showing any datas when i start the webserver.

I code on Pycharm on a Win11 without GPU.

I don't know where I did wrong.

Thanks and have a nice day.

**Comment by georkara** [comment]
Hello ocekic, 
Please try to follow instructions to avoid such problems. Maybe this is a problem with the path. When you run for example DDPG_train.py then within the folder that this .py file is located two subfolders will be created storing each time a new trained model. If the file can't be found then for me it is clear that there is wrong path. But I am a bit of confused as I think that this is already in an automated manner. Same is for tensorboard. Please check the indicated example how to use tensorboard or check its core commands. You should call that specific command in terminal under the correct path.

**Comment by georkara** [comment]
Ah, you included double zip ending.  you did a typo mistake - > 'models\DDPG-1685441307\80000.zip.zip'
use  'models/DDPG-1685441307/80000.zip' instead.

**Comment by ocekic** [comment]
Hello Georkara,

Thanks for the fast answer.

Euh I'm confused because I didn't change the code. I don't understand why there is .zip.zip.

the code => 
```
#Define which model to load
models_dir1="models/DDPG-1646748022"
model_path1=f"{models_dir1}/940000.zip"
model1 = DDPG.load(model_path1, env=env
```

Thanks for your comment with tensorboard, it's working !

Thanks and have a nice day.

**Comment by ocekic** [comment]
Is the tensorboard is enough for the comparaison of the algorithms or the evaluate_trained_models.py is necessary ? Because it's just the evaluate_trained_models.py who isn't working for me.

**Comment by georkara** [comment]
With tensorboard you just monitor the training phase and the evolution of reward during this phase. With "evaluate_trained_models.py" you practically evaluate the performance of a chosen trained model. Thus, "940000.zip" means that you take this specific trained model from the whole sequence of training, in order to evaluate this specific one model.

for  "evaluate_trained_models.py" you have to choose your model. "DDPG-1646748022" is the indicated example that i provided. I guess that you already have this -> models/DDPG-1685441307, as you indicated above. Change this and it will work.

Use the following please and generally have in mind " / " and " \ " difference.
#Define which model to load
models_dir1="models/DDPG-1685441307"
model_path1=f"{models_dir1}/80000.zip"

**Comment by ocekic** [comment]
Ok, I tried this code : 

```python
#Define which model to load
models_dir1 = "models/DDPG-1685688892"
model_path1 = f"{models_dir1}/20000.zip"
print(model_path1)
model1 = DDPG.load(model_path1, env=env)
```

My directory : 
![image](https://github.com/georkara/Chargym-Charging-Station/assets/96057877/0fc2cb66-b119-4dfb-bd1d-7bd18ba85e95)

I opened Pycharm in admin mode, maybe it was Windows who didn't let Pycharm to get the .zip file.

Here is the result : 

```
Traceback (most recent call last):
  File "C:\Users\Utilisateur\Documents\GitHub\Chargym-Charging-Station\Solvers\evaluate_trained_models.py", line 28, in <module>
    model1 = DDPG.load("models/DDPG-1685688892/20000.zip", env=env)
  File "C:\Users\Utilisateur\Documents\GitHub\Chargym-Charging-Station\venv\lib\site-packages\stable_baselines3\common\base_class.py", line 688, in load
    path, device=device, custom_objects=custom_objects, print_system_info=print_system_info
  File "C:\Users\Utilisateur\Documents\GitHub\Chargym-Charging-Station\venv\lib\site-packages\stable_baselines3\common\save_util.py", line 388, in load_from_zip_file
    load_path = open_path(load_path, "r", verbose=verbose, suffix="zip")
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Utilisateur\Documents\GitHub\Chargym-Charging-Station\venv\lib\site-packages\stable_baselines3\common\save_util.py", line 232, in open_path_str
    return open_path(pathlib.Path(path), mode, verbose, suffix)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Utilisateur\Documents\GitHub\Chargym-Charging-Station\venv\lib\site-packages\stable_baselines3\common\save_util.py", line 284, in open_path_pathlib
    return open_path(path, mode, verbose, suffix)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Utilisateur\Documents\GitHub\Chargym-Charging-Station\venv\lib\site-packages\stable_baselines3\common\save_util.py", line 264, in open_path_pathlib
    raise error
  File "C:\Users\Utilisateur\Documents\GitHub\Chargym-Charging-Station\venv\lib\site-packages\stable_baselines3\common\save_util.py", line 256, in open_path_pathlib
    path = path.open("rb")
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1208, in open
    opener=self._opener)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'models\\DDPG-1685688892\\20000.zip.zip'
models/DDPG-1685688892/20000.zip

Process finished with exit code 1
```

I also added a print to see if the path is correct. 

Thanks for your answer.

**Comment by shuiseyouyang6** [comment]
I have the same problem. Can you tell me how you solved it?

**Comment by ocekic** [comment]
Hello @shuiseyouyang6, I didn't solved the problem, I just trained my agent and I looked at it with the tensorboard. I suppose it was hardware problem in my case because I also had a bad computer.

Have a nice day.

**Comment by lqhdehub** [comment]
Hello, I had the same error before, but after changing its path to absolute path, this error will not be  reported.
<img width="518" alt="屏幕截图 2024-01-26 204330" src="https://github.com/georkara/Chargym-Charging-Station/assets/145434218/ae9e920a-60cd-4604-95bf-82a9f3c30569">

**Comment by Electric-V** [comment]
There may be some problems with the case code path given, you can try this:

models_dir1 = "./RL/models/DDPG-1712128012"
model_path1 = f"{models_dir1}/980000.zip"
model1 = DDPG.load(model_path1, env=env)

models_dir2 = "./RL/models/PPO-1711885575"
model_path2 = f"{models_dir2}/980000.zip"
model2 = PPO.load(model_path2, env=env)

![image](https://github.com/georkara/Chargym-Charging-Station/assets/151052180/39b0476e-7971-4359-ad4d-3dda201f3097)

**Comment by xing-ji63** [comment]
<img width="837" alt="Image" src="https://github.com/user-attachments/assets/0088b5bf-a016-48bb-8211-e40aa47d6d87" />
Thank you very much for sharing the project with the blogger. Excuse me, did you encounter any issues with the image while running the above file? I tried for a long time but couldn't solve it. But running the code a few times will make it run successfully.

**Comment by lamdaxi1234** [comment]
Hello! Could you please add the files "DDPG-1646748022" and "PPO-1646764100" model and log to the repository, according to indicative_tensorboard.py? It would be very helpfull. Thanks in advance!
